version: '3.0'
services:
  rasa:
    build: .
    ports:
      - "5005:5005" # Exposed directly to host for testing
    environment:
      - PORT=5005
    restart: always
    volumes:
      # - ./models:/app/models # Commented out to use the model trained during build
      - ./data:/app/data
      - ./config.yml:/app/config.yml
      - ./domain.yml:/app/domain.yml
      - ./credentials.yml:/app/credentials.yml

  action-server:
    build: .
    entrypoint: [ "/bin/bash", "/usr/bin/start-actions.sh" ]
    user: root
    environment:
      - SANIC_HOST=0.0.0.0
    ports:
      - "5055:5055"
    volumes:
      - ./data:/app/data
      - ./files:/app/files
      - ./fonts:/app/fonts
      - ./actions:/app/actions
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./files:/usr/share/nginx/html/files
      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
      - rasa

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  admin-app:
    build: .
    entrypoint: []
    command: streamlit run admin_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./files:/app/files
      - ./admin_app.py:/app/admin_app.py
    restart: always
